from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List, Optional
import uuid

from app.db.session import get_db
from app.models.report import Report
from app.models.case import Case
from app.schemas.report import ReportResponse, ReportStatusResponse
from app.dependencies import get_current_user
from app.models.user import User
from app.core.rbac import require_roles
from app.db.base import Role, AuditAction
from app.core.audit import log_action
from app.services.storage import get_presigned_url
from app.config import settings

router = APIRouter()

# Doctor only
require_doctor = require_roles(Role.Doctor)

@router.get("/{case_id}", response_model=ReportResponse, dependencies=[Depends(require_doctor)])
async def get_report(
    case_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    stmt = select(Report).where(Report.case_id == case_id)
    result = await db.execute(stmt)
    report = result.scalar_one_or_none()
    
    if not report:
        raise HTTPException(status_code=404, detail="Report not generated yet for this case.")
        
    # Generate fresh presigned URL for downloading
    if report.pdf_url:
        short_lived_url = get_presigned_url(settings.MINIO_BUCKET_REPORTS, report.pdf_url)
        # We temporarily swap the db URL for the signed URL on the returned Pydantic object
        report.pdf_url = short_lived_url
    
    await log_action(db, AuditAction.REPORT_DOWNLOADED, user_id=current_user.user_id, case_id=case_id)
    
    return report

@router.get("/{case_id}/status", response_model=ReportStatusResponse, dependencies=[Depends(require_doctor)])
async def get_report_status(
    case_id: uuid.UUID,
    db: AsyncSession = Depends(get_db)
):
    stmt = select(Report).where(Report.case_id == case_id)
    result = await db.execute(stmt)
    report = result.scalar_one_or_none()
    
    if report:
        return {"status": "ready", "report_id": report.report_id}
        
    # TODO: Check celery task state. Using "generating" for mock logic.
    return {"status": "generating", "report_id": None}

@router.get("/", response_model=List[ReportResponse], dependencies=[Depends(require_doctor)])
async def list_reports(
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    # Only return reports generated by the currently logged-in doctor
    stmt = select(Report).where(Report.generated_by == current_user.user_id).offset(skip).limit(limit)
    result = await db.execute(stmt)
    return result.scalars().all()

@router.post("/{case_id}/regenerate", status_code=status.HTTP_202_ACCEPTED, dependencies=[Depends(require_doctor)])
async def regenerate_report(
    case_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    stmt = select(Report).where(Report.case_id == case_id)
    result = await db.execute(stmt)
    report = result.scalar_one_or_none()
    
    if report:
        db.delete(report)
        await db.commit()
    
    # TODO: Phase 6 trigger Celery background worker to compile the final PDF Report
    # generate_report.delay(str(case_id), str(current_user.user_id))
    
    return {"message": "Report generation enqueued."}
